version: "3"

services:
    web:
        container_name: exampleapp
        restart: always
        build: .
        ports:
            - "5000:3000"
        links: 
            - mongo
        volumes:
            - ./src:/usr/src/app1/src  #Modifica los archivos en el docker compose
    mongo:
        container_name: mymongodatabase
        image: mongo
        ports:
            - "27018:27017"
        logging: 
            driver: none